name: Tests
run-name: ${{ github.actor }} triggered Tests
on:
  push: ~
permissions:
  contents: read
  id-token: write
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v3
      - run: |
          docker build --cache-to type=gha,mode=max --cache-from type=gha -t app .
      - name: psalm
        run: docker run app vendor/bin/psalm
      - name: Test ambiguous-classes
        run: |
          set -ex
          docker run app bin/ambiguous-classes dummy/ambiguous-classes/without-errors
          docker run app bin/ambiguous-classes dummy/ambiguous-classes/with-errors --baseline > ambiguous-classes.baseline
          docker run app bin/ambiguous-classes dummy/ambiguous-classes/with-errors --ignore-baseline=ambiguous-classes.baseline
          # We negate the exit code, because we expect an error
          docker run app bin/ambiguous-classes dummy/ambiguous-classes/with-errors || exit 0
          