name: Tests
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push: ~
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - name: Psalm
        uses: docker://ghcr.io/psalm/psalm-github-actions